name: loker_airbridge
description: "Loker Airbridge"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  freezed_annotation: ^3.0.0
  go_router: ^15.1.0
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
